name = "Pioche"
license = "MIT"
licenselink = "https://github.com/ludovicm67/pioche/blob/master/LICENSE"
description = ""
homepage = "https://ludovicm67.github.io/pioche/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "ludovicm67"
  homepage = "https://www.ludovic-muller.fr/"
